var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 12;
myBool = true;
myVar = false;
strArr = ['Hello', 'World'];
numArr = [4, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['asdf', 3];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myVoid);
